[package]
name = "citron"
version = "0.1.0"
authors = ["Emiliano Firmino <emiliano.firmino@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"